# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 大同
email: temberature@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  编程技术分享为主，偏前端、javaScript
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: tiandatong
github_username:  temberature

# Build settings
markdown: kramdown
